### ISSUE TITLE
clipboard-event-handler Initilization Failing

### ISSUE THREAD

**Issue by agentgodzilla** [langedechu/auto-paste-kde-emoji#1]
I went to try this out, but am having issues with clipboard-event-handler.  I'm not a JS dev so was hoping you had some advise for working through this?  Should I try a specific bun version?  It is saying it cannot find the executable for `clipboard-event-hander-linux` even though it does exist in expected location.

> sudo rm /usr/local/bin/auto-paste-kde-emoji
> rm -rf ~/.auto-paste-kde-emoji
> rm -rf auto-paste-kde-emoji/
> 
> git clone https://github.com/langedechu/auto-paste-kde-emoji.git
> Cloning into 'auto-paste-kde-emoji'...
> remote: Enumerating objects: 31, done.
> remote: Counting objects: 100% (31/31), done.
> remote: Compressing objects: 100% (20/20), done.
> remote: Total 31 (delta 12), reused 30 (delta 11), pack-reused 0 (from 0)
> Receiving objects: 100% (31/31), 8.68 KiB | 8.68 MiB/s, done.
> Resolving deltas: 100% (12/12), done.
> 
> cd auto-paste-kde-emoji/
> bun --version
> 1.1.30
> chmod +x ./install.sh
> ./install.sh
> bun install v1.1.30 (7996d06b)
> 
> + typescript@5.2.2
> + bun-types@1.0.9
> + clipboard-event@1.6.0
> + clipboardy@4.0.0
> 
> 26 packages installed [7.00ms]
> 
> if test -f /home/me/.auto-paste-kde-emoji/node_modules/clipboard-event/platform/clipboard-event-handler-linux; then echo file exists; fi
> file exists
> 
> auto-paste-kde-emoji
> 13 |     const { platform } = process;
> 14 |     if (platform === 'win32') {
> 15 |       this.child = execFile(path.join(__dirname, 'platform/clipboard-event-handler-win32.exe'));
> 16 |     }
> 17 |     else if (platform === 'linux') {
> 18 |       this.child = execFile(path.join(__dirname, 'platform/clipboard-event-handler-linux'));
>                         ^
> TypeError: Executable not found in $PATH: "/home/me/.auto-paste-kde-emoji/node_modules/clipboard-event/platform/clipboard-event-handler-linux"
>  code: "ERR_INVALID_ARG_TYPE"
> 
>       at spawn (node:child_process:758:8)
>       at spawn (node:child_process:2:15)
>       at execFile (node:child_process:38:18)
>       at startListening (/home/me/.auto-paste-kde-emoji/node_modules/clipboard-event/index.cjs:18:20)
>       at /home/me/.auto-paste-kde-emoji/index.ts:6:19
> 
> Bun v1.1.30 (Linux x64)
> lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 24.04.1 LTS
> Release:        24.04
> Codename:       noble

**Comment by mableinhell** [comment]
Hey, thanks for reaching out! Can the file be executed ? You can see it in its properties, or directly grant the executable permission over this command : `chmod +x path/to/the/clipboard-event-handler-linux`. Hope this helps, if not I'm willing to do some debugging here. Have a great day!

**Comment by agentgodzilla** [comment]
That was it, I should've thought of that, thanks for the quick response
